version: '2'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: host
    volumes:
      - ./grafana/data:/var/lib/grafana # Grafana data
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    network_mode: host
        