services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: root
    ports:
      - '9090:9090' # Port for Prometheus UI
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus

    networks:
      monitoring-network:
        ipv4_address: 192.168.11.4

  monitoring-caddy:
    image: caddy:2.8.4
    container_name: monitoring-caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
    env_file:
      - .env
    networks:
      monitoring-network:
        ipv4_address: 192.168.11.6

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    user: root
    volumes:
      - ./grafana/data:/var/lib/grafana # Grafana data
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      monitoring-network:
        ipv4_address: 192.168.11.7

networks:
  monitoring-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.11.0/24
          gateway: 192.168.11.1
