global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'juneogo-machine'
    metrics_path: '/metrics'
    scheme: 'https'
    basic_auth:
      username: 'TODO'
      password: 'TODO'
    static_configs:
      - targets: ['your-domain.com']
        labels:
          server: 'your-server-name'
      - targets: ['your-domain-2.com']
        labels:
          server: 'your-server-name-2'

  - job_name: 'juneogo'
    metrics_path: '/ext/metrics'
    scheme: 'https'
    basic_auth:
      username: 'TODO'
      password: 'TODO'
    static_configs:
      - targets: ['your-domain.com']
        labels:
          server: 'your-server-name'
      - targets: ['your-domain-2.com']
        labels:
          server: 'your-server-name-2'
