global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.11.4:9090']

  - job_name: 'juneogo-machine'
    static_configs:
      - targets: ['192.168.11.5:9100']

  - job_name: "juneogo"
    metrics_path: "/ext/metrics"
    scheme: "http"
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['192.168.10.2:9650']