{
 "title": "All nodes",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(juneomcn_network_node_uptime_weighted_average, server)"
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Percentage of CPU used",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"juneogo-machine\",server=\"$node\", mode=\"idle\"}[1m])) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "description": "GB of memory free",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=~\"juneogo-machine\",server=\"$node\" })",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "(node_memory_MemFree_bytes{job=~\"juneogo-machine\",server=\"$node\"})",
     "legendFormat": "Available Memory"
    }
   ]
  },
  {
   "title": "Memory Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes{job=~\"juneogo-machine\",server=\"$node\"} - node_memory_MemFree_bytes{job=~\"juneogo-machine\",server=\"$node\"} - node_memory_Buffers_bytes{job=~\"juneogo-machine\",server=\"$node\"} - node_memory_Cached_bytes{job=~\"juneogo-machine\",server=\"$node\"}) / node_memory_MemTotal_bytes{job=~\"juneogo-machine\",server=\"$node\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Node stake",
   "type": "stat",
   "description": "Amount of JUNE currently staked",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "juneomcn_P_vm_local_staked{job=\"juneogo\",server=\"$node\"} / 1000000000",
     "legendFormat": "JUNE"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "stat",
   "description": "GB of storage free",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{job=~\"juneogo-machine\",server=\"$node\", fstype=~\"ext4|vfat\"}) )",
     "legendFormat": "Total Disk space"
    },
    {
     "expr": "(node_filesystem_avail_bytes{job=~\"juneogo-machine\",server=\"$node\", fstype=~\"ext4|vfat\"})",
     "legendFormat": "Available Disk Space"
    }
   ]
  },
  {
   "title": "Uptime average",
   "type": "gauge",
   "description": "Stake weighted average uptime of your node, as reported by network peers. If this falls below 80% node probably won't be rewarded for the current staking period.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "juneomcn_network_node_uptime_weighted_average{job=\"juneogo\",server=\"$node\"}"
    }
   ]
  }
 ]
}