{
 "title": "Database",
 "tags": [ "Juneo" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(juneomcn_network_node_uptime_weighted_average, server)"
   }
  ]
 },
 "panels": [
  {
   "title": "Database Read Rate",
   "type": "timeseries",
   "description": "Database read rate. Note that these reads may be from caches and not from disk.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(juneomcn_db_read_size_sum{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "Bytes Read"
    }
   ]
  },
  {
   "title": "Database Write Rate",
   "type": "timeseries",
   "description": "Database write rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(juneomcn_db_write_size_sum{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "Write Rate"
    }
   ]
  },
  {
   "title": "Total Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second across all chains",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(juneomcn_db_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(juneomcn_db_get_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(juneomcn_db_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(juneomcn_db_has_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(juneomcn_db_compact_size_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(juneomcn_db_batch_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(juneomcn_db_batch_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(juneomcn_db_batch_reset_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(juneomcn_db_batch_replay_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "Total Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(juneomcn_db_put_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(juneomcn_db_get_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_get_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(juneomcn_db_delete_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(juneomcn_db_has_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_has_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(juneomcn_db_compact_size_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_compact_size_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(juneomcn_db_batch_put_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_batch_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(juneomcn_db_batch_delete_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_batch_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(juneomcn_db_batch_reset_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_batch_reset_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(juneomcn_db_batch_replay_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_batch_replay_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "JVM-Chain Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second on JVM-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(juneomcn_JVM_db_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(juneomcn_JVM_db_get_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(juneomcn_JVM_db_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(juneomcn_JVM_db_has_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(juneomcn_JVM_db_compact_size_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(juneomcn_JVM_db_batch_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(juneomcn_JVM_db_batch_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(juneomcn_JVM_db_batch_reset_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(juneomcn_JVM_db_batch_replay_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "JVM-Chain Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average on JVM-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(juneomcn_JVM_db_put_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JVM_db_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(juneomcn_JVM_db_get_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JVM_db_get_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(juneomcn_JVM_db_delete_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JVM_db_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(juneomcn_JVM_db_has_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JVM_db_has_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(juneomcn_JVM_db_compact_size_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JVM_db_compact_size_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(juneomcn_JVM_db_batch_put_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JVM_db_batch_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(juneomcn_JVM_db_batch_delete_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JVM_db_batch_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(juneomcn_JVM_db_batch_reset_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JVM_db_batch_reset_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(juneomcn_JVM_db_batch_replay_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JVM_db_batch_replay_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "P-Chain Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second on P-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(juneomcn_P_db_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(juneomcn_P_db_get_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(juneomcn_P_db_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(juneomcn_P_db_has_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(juneomcn_P_db_compact_size_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(juneomcn_P_db_batch_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(juneomcn_P_db_batch_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(juneomcn_P_db_batch_reset_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(juneomcn_P_db_batch_replay_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "P-Chain Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average on P-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(juneomcn_P_db_put_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_P_db_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(juneomcn_P_db_get_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_P_db_get_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(juneomcn_P_db_delete_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_P_db_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(juneomcn_P_db_has_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_P_db_has_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(juneomcn_P_db_compact_size_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_P_db_compact_size_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(juneomcn_P_db_batch_put_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_P_db_batch_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(juneomcn_P_db_batch_delete_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_P_db_batch_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(juneomcn_P_db_batch_reset_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_P_db_batch_reset_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(juneomcn_P_db_batch_replay_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_P_db_batch_replay_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "JUNE-Chain Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second across all chains",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(juneomcn_JUNE_db_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(juneomcn_JUNE_db_get_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(juneomcn_JUNE_db_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(juneomcn_JUNE_db_has_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(juneomcn_JUNE_db_compact_size_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(juneomcn_JUNE_db_batch_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(juneomcn_JUNE_db_batch_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(juneomcn_JUNE_db_batch_reset_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(juneomcn_JUNE_db_batch_replay_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "JUNE-Chain Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average on JUNE-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(juneomcn_JUNE_db_put_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JUNE_db_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(juneomcn_JUNE_db_get_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JUNE_db_get_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(juneomcn_JUNE_db_delete_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JUNE_db_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(juneomcn_JUNE_db_has_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JUNE_db_has_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(juneomcn_JUNE_db_compact_size_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JUNE_db_compact_size_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(juneomcn_JUNE_db_batch_put_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JUNE_db_batch_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(juneomcn_JUNE_db_batch_delete_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JUNE_db_batch_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(juneomcn_JUNE_db_batch_reset_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JUNE_db_batch_reset_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(juneomcn_JUNE_db_batch_replay_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_JUNE_db_batch_replay_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  }
 ]
}