{
 "title": "Juneo Main Dashboard",
 "description": "Home dashboard with the most important indicators for your node and machine",
 "tags": [ "Juneo" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(juneomcn_network_node_uptime_weighted_average, server)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime average",
   "type": "gauge",
   "description": "Stake weighted average uptime of your node, as reported by network peers. If this falls below 80% node probably won't be rewarded for the current staking period.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "juneomcn_network_node_uptime_weighted_average{job=\"juneogo\",server=\"$node\"}"
    }
   ]
  },
  {
   "title": "Rewarding stake",
   "type": "gauge",
   "description": "Percentage of the stake that view your node as sufficiently online and correct to vote that node be awarded at the end of the staking period.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "juneomcn_network_node_uptime_rewarding_stake{job=\"juneogo\",server=\"$node\"}",
     "legendFormat": "Rewarding stake"
    }
   ]
  },
  {
   "title": "JVM Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the JVM chain in the last minute",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(juneomcn_JVM_blks_accepted_count{job=\"juneogo\",server=\"$node\"}[1m]))>0",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(juneomcn_JVM_blks_rejected_count{job=\"juneogo\",server=\"$node\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Proposed JVM blocks",
   "type": "stat",
   "description": "Number of JVM-Chain blocks this node has proposed on the network in the last day. Since block production on P-Chain is usually below the target rate, every node proposes P blocks.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(juneomcn_JVM_blks_built{job=\"juneogo\",server=\"$node\"}[1d]))",
     "legendFormat": "Proposed P blocks"
    }
   ]
  },
  {
   "title": "P Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the P chain in the last minute.",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(juneomcn_P_blks_accepted_count{job=\"juneogo\",server=\"$node\"}[1m]))>0",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(juneomcn_P_blks_rejected_count{job=\"juneogo\",server=\"$node\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Proposed P blocks",
   "type": "stat",
   "description": "Number of P-Chain blocks this node has proposed on the network in the last day. Since block production on P-Chain is usually below the target rate, every node proposes P blocks.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(juneomcn_P_blks_built{job=\"juneogo\",server=\"$node\"}[1d]))",
     "legendFormat": "Proposed P blocks"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Percentage of CPU used",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{job=~\"juneogo-machine\",server=\"$node\", mode=\"idle\"}[1m])) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "gauge",
   "description": "Percentage of storage filled",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(((node_filesystem_size_bytes{job=~\"juneogo-machine\",server=\"$node\", fstype=~\"ext4|vfat\"} - node_filesystem_free_bytes{job=~\"juneogo-machine\",server=\"$node\", fstype=~\"ext4|vfat\"}) / node_filesystem_size_bytes{job=~\"juneogo-machine\",server=\"$node\", fstype=~\"ext4|vfat\"}) * 100) by (instance)"
    }
   ]
  },
  {
   "title": "Failing health checks",
   "type": "gauge",
   "description": "Number of currently failing internal health checks",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "juneomcn_health_checks_failing{job=\"juneogo\",server=\"$node\",tag=\"all\"}"
    }
   ]
  },
  {
   "title": "Network Latency",
   "type": "stat",
   "description": "Average time to get a response from a peer",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "juneomcn_requests_average_latency{job=\"juneogo\",server=\"$node\"}"
    }
   ]
  },
  {
   "title": "Total staked",
   "type": "stat",
   "description": "Amount of JUNE currently staked",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "juneomcn_P_vm_total_staked{job=\"juneogo\",server=\"$node\"}/1000000000",
     "legendFormat": "JUNE"
    }
   ]
  },
  {
   "title": "Stake connected",
   "type": "stat",
   "description": "Amount of network stake node is currently connected to",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "juneomcn_P_vm_percent_connected{job=\"juneogo\",server=\"$node\"}"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "timeseries",
   "description": "Number of peers node is connected to",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "juneomcn_network_peers{job=\"juneogo\",server=\"$node\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "JUNE Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the JUNE chain in the last minute.",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(juneomcn_JUNE_blks_accepted_count{job=\"juneogo\",server=\"$node\"}[1m]))>0",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(juneomcn_JUNE_blks_rejected_count{job=\"juneogo\",server=\"$node\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Proposed JUNE blocks",
   "type": "stat",
   "description": "Number of blocks this node has proposed on the JUNE-Chain in the last day. Since JUNE-Chain blocks are produced at a fast rate, block producers are selected by stake weight.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(juneomcn_JUNE_blks_built{job=\"juneogo\",server=\"$node\"}[1d]))",
     "legendFormat": "Built JUNE blocks"
    }
   ]
  },
  {
   "title": "Accepted Blocks",
   "type": "bargauge",
   "description": "Number of blocks accepted in the last minute",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(juneomcn_JVM_blks_accepted_count{job=\"juneogo\",server=\"$node\"}[1m]))",
     "legendFormat": "JVM Chain"
    },
    {
     "expr": "round(increase(juneomcn_P_blks_accepted_count{job=\"juneogo\",server=\"$node\"}[1m]))",
     "legendFormat": "P Chain"
    },
    {
     "expr": "round(increase(juneomcn_JUNE_blks_accepted_count{job=\"juneogo\",server=\"$node\"}[1m]))",
     "legendFormat": "JUNE Chain"
    }
   ]
  },
  {
   "title": "Blocks processing",
   "type": "bargauge",
   "description": "Number of blocks currently being processed by the node",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "juneomcn_JVM_blks_processing{job=\"juneogo\",server=\"$node\"}",
     "legendFormat": "JVM Chain"
    },
    {
     "expr": "juneomcn_P_blks_processing{job=\"juneogo\",server=\"$node\"}",
     "legendFormat": "P Chain"
    },
    {
     "expr": "juneomcn_JUNE_blks_processing{job=\"juneogo\",server=\"$node\"}",
     "legendFormat": "JUNE Chain"
    }
   ]
  },
  {
   "title": "Benched nodes",
   "type": "bargauge",
   "description": "Number of peers currently being benched (ignored) by the node",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "juneomcn_JVM_benchlist_benched_num{job=\"juneogo\",server=\"$node\"}",
     "legendFormat": "JVM Chain"
    },
    {
     "expr": "juneomcn_P_benchlist_benched_num{job=\"juneogo\",server=\"$node\"}",
     "legendFormat": "P Chain"
    },
    {
     "expr": "juneomcn_JUNE_benchlist_benched_num{job=\"juneogo\",server=\"$node\"}",
     "legendFormat": "JUNE Chain"
    }
   ]
  },
  {
   "title": "Queries success",
   "type": "bargauge",
   "description": "Percentage of successful queries per chain in the last minute",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(juneomcn_JVM_handler_chits_count{job=\"juneogo\",server=\"$node\"}[1m]) + 1) / (increase(juneomcn_JVM_handler_chits_count{job=\"juneogo\",server=\"$node\"}[1m]) + increase(juneomcn_JVM_handler_query_failed_count{job=\"juneogo\",server=\"$node\"}[1m]) + 1)",
     "legendFormat": "JVM Chain"
    },
    {
     "expr": "(increase(juneomcn_P_handler_chits_count{job=\"juneogo\",server=\"$node\"}[1m]) + 1) / (increase(juneomcn_P_handler_chits_count{job=\"juneogo\",server=\"$node\"}[1m]) + increase(juneomcn_P_handler_query_failed_count{job=\"juneogo\",server=\"$node\"}[1m]) + 1)",
     "legendFormat": "P Chain"
    },
    {
     "expr": "(increase(juneomcn_JUNE_handler_chits_count{job=\"juneogo\",server=\"$node\"}[1m]) + 1) / (increase(juneomcn_JUNE_handler_chits_count{job=\"juneogo\",server=\"$node\"}[1m]) + increase(juneomcn_JUNE_handler_query_failed_count{job=\"juneogo\",server=\"$node\"}[1m]) + 1)",
     "legendFormat": "JUNE Chain"
    }
   ]
  },
  {
   "title": "Database Operations Latency",
   "type": "timeseries",
   "description": "How long each database operation is taking on average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(juneomcn_db_put_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(juneomcn_db_get_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_get_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(juneomcn_db_delete_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(juneomcn_db_has_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_has_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(juneomcn_db_compact_size_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_compact_size_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(juneomcn_db_batch_put_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_batch_put_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(juneomcn_db_batch_delete_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_batch_delete_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(juneomcn_db_batch_reset_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_batch_reset_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(juneomcn_db_batch_replay_sum{job=\"juneogo\",server=\"$node\"}[5m])/increase(juneomcn_db_batch_replay_count{job=\"juneogo\",server=\"$node\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  }
 ]
}