apiVersion: 1
groups:
    - orgId: 1
      name: stake
      folder: stake
      interval: 1m
      rules:
        - uid: stake_rule_socotra
          title: stake_rule_socotra
          condition: TRESH
          data:
            - refId: STAKE
              relativeTimeRange:
                from: 10
                to: 0
              datasourceUid: JuneogoPrometheusSocotra
              model:
                editorMode: code
                expr: node_list
                instant: false
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: STAKE
            - refId: RED
              relativeTimeRange:
                from: 10
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: STAKE
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: RED
                type: reduce
            - refId: TRESH
              relativeTimeRange:
                from: 10
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.9
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: RED
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: TRESH
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations: 
            Value: "{{ $values.RED }}"
          labels: {}
          isPaused: false
          notification_settings:
            receiver: telegram-contact-point-socotra
            repeat_interval: 1m

        - uid: stake_rule_mainnet
          title: stake_rule_mainnet
          condition: TRESH
          data:
            - refId: STAKE
              relativeTimeRange:
                from: 10
                to: 0
              datasourceUid: JuneogoPrometheusMainnet
              model:
                editorMode: code
                expr: node_list
                instant: false
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: STAKE
            - refId: RED
              relativeTimeRange:
                from: 10
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: STAKE
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: RED
                type: reduce
            - refId: TRESH
              relativeTimeRange:
                from: 10
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.9
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: RED
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: TRESH
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations: 
            Value: "{{ $values.RED }}"
          labels: {}
          isPaused: false
          notification_settings:
            receiver: telegram-contact-point-mainnet
            repeat_interval: 1m

        - uid: stake_rule_banana
          title: stake_rule_banana
          condition: TRESH
          data:
            - refId: STAKE
              relativeTimeRange:
                from: 10
                to: 0
              datasourceUid: JuneogoPrometheusBanana
              model:
                editorMode: code
                expr: node_list
                instant: false
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: STAKE
            - refId: RED
              relativeTimeRange:
                from: 10
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: STAKE
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: RED
                type: reduce
            - refId: TRESH
              relativeTimeRange:
                from: 10
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.9
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: RED
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: TRESH
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations: 
            Value: "{{ $values.RED }}"
          labels: {}
          isPaused: false
          notification_settings:
            receiver: telegram-contact-point-sponsored
            repeat_interval: 1m

    - orgId: 1
      name: disk_space
      folder: disk_space
      interval: 120m
      rules:
        - uid: disk_space_socotra
          title: disk_space_socotra
          condition: RED
          data:
            - refId: SPACE
              relativeTimeRange:
                from: 10
                to: 0
              datasourceUid: JuneogoPrometheusSocotra
              model:
                editorMode: code
                expr: node_list_low_space
                instant: false
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: SPACE
            - refId: RED
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: SPACE
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: RED
                type: reduce
          noDataState: OK
          execErrState: Error
          for: 1h
          annotations:
            Value: '{{ $values.RED }} Go'
            description: ""
            runbook_url: ""
            summary: ""
          labels:
            "": ""
          isPaused: false
          notification_settings:
            receiver: telegram-contact-point-socotra
            repeat_interval: 1m

        # -------- Mainnet --------
        - uid: disk_space_mainnet
          title: disk_space_mainnet
          condition: RED
          data:
            - refId: SPACE
              relativeTimeRange:
                from: 10
                to: 0
              datasourceUid: JuneogoPrometheusMainnet
              model:
                editorMode: code
                expr: node_list_low_space
                instant: false
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: SPACE
            - refId: RED
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: SPACE
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: RED
                type: reduce
          noDataState: OK
          execErrState: Error
          for: 1h
          annotations:
            Value: '{{ $values.RED }} Go'
            description: ""
            runbook_url: ""
            summary: ""
          labels:
            "": ""
          isPaused: false
          notification_settings:
            receiver: telegram-contact-point-mainnet
            repeat_interval: 1m

        - uid: disk_space_banana
          title: disk_space_banana
          condition: RED
          data:
            - refId: SPACE
              relativeTimeRange:
                from: 10
                to: 0
              datasourceUid: JuneogoPrometheusBanana
              model:
                editorMode: code
                expr: node_list_low_space
                instant: false
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: SPACE
            - refId: RED
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: SPACE
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: RED
                type: reduce
          noDataState: OK
          execErrState: Error
          for: 1h
          annotations:
            Value: '{{ $values.RED }} Go'
            description: ""
            runbook_url: ""
            summary: ""
          labels:
            "": ""
          isPaused: false
          notification_settings:
            receiver: telegram-contact-point-sponsored
            repeat_interval: 1m
